### ISSUE TITLE
[BUG] 2.3.5 could not build arguments for function "reflect".makeFuncStub

### ISSUE THREAD

**Issue by felixishim** [bittorrent/go-btfs#420]
**Describe the bug**
After updating to 2.3.5 my daemon does not go further then vault implementation is updated.
When I ran btfs storage hosts info, i  received the following error:

`Error: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *mfs.Root: received non-nil error from function "github.com/bittorrent/go-btfs/core/node".Files (/go-btfs/core/node/core.go:131): error loading filesroot from DAG: block was not found locally (offline): ipld: could not find bafkreicjmmccca4fa62hl24bldb3dp754hucju3xhnitfnmsk4swcun2um`

**To Reproduce**
1. Execute command ' btfs storage hosts info,.'
2. See error

**Desktop (please complete the following information):**
 - OS: Windows 11
