### ISSUE TITLE
[BUG] bitswap providerquerymanager.go:338 ERROR

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#290]
Clicking on dashboard links results in this error, data appears possibly not affected but I do not know the impact of this error or how to fix it.

**To Reproduce**
Click on dashboard links, see error pop up on CMD prompt screen.

**Expected behavior**
Dashboard links should work without BTFS kicking out this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/42473932/207779127-9dfb92b4-c577-4a9b-9228-6318f58fac05.png)

**Desktop (please complete the following information):**
 - OS: Windows 20 Pro
 - Version: OS Build 19044.2251

**Additional context**
This is after I updated from 2.2.1.1 and performed the following steps:
1. Stop v2.2.1.1 BTFS daemon process
2. Open the BTFS config file: C:/Users/RMi/.btfs/config
3. Find the line "Endpoint": "https://rpc.bittorrentchain.io/"
4. Replace https://rpc.bittorrentchain.io/ to https://rpc.bt.io/
5. Start v2.3.0 BTFS daemon again

**Comment by oldcityws** [comment]
The text of the error is:

2022-12-15T00:03:45.847-0500    ←[31mERROR←[0m  bitswap providerquerymanager/providerquerymanager.go:338        Received provider (16Uiu2HAmQLbNGHn3D6X6AeqpcZrpARGPCs4EwbpazuZZ9n88dEzP) for cid (QmbDp8LUTP88ERqaFZfuRv8pjW4PhCNDF19HAfjJEDrmSe) not requested
2022-12-15T00:17:43.947-0500    ←[31mERROR←[0m  bitswap providerquerymanager/providerquerymanager.go:338        Received provider (16Uiu2HAmPnLKzMkV1B5G8MpavWcvzqhTUUenFugHdEeDajoirneP) for cid (QmaXYXvbj1cJqeZ18Kj67sRSUGeTJZs17Lpzr7fJV2appP) not requested

And I noticed that loading the dashboard coincided with the first error message produced.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207781312-8fa53ad9-1d62-4e9e-9aa7-56f4e0f98d96.png)
And the BTTC address + Vault Contract Address show 0 BTT and no Vault Contract Address until after I've refreshed the page by clicking the F5 key several times.

**Comment by oldcityws** [comment]
And here it is, after clicking links and then clicking F5 about a dozen times...
![image](https://user-images.githubusercontent.com/42473932/207781835-b61e6bc8-e2b4-4ad9-9902-722b5307dbc6.png)

**Comment by imstevez** [comment]
The first issue is same with https://github.com/bittorrent/go-btfs/issues/289，and it seems can be ignored.

**Comment by imstevez** [comment]
The second issue may be caused by the browser cache, and It is good now, will not go out again

**Comment by oldcityws** [comment]
Thanks, that's what I had thought, just wanted to make sure it can be ignored.
